### ISSUE TITLE
Remove Files ending with ~

### ISSUE THREAD

**Issue by subins2000** [FOSSersVAST/fossweb#10]
Some files were edited with `gedit`. `gedit` makes a backup of the file with ending `~` and some added this file to git causing a lot of unwanted files in the repository.

Examples : 
* [`creative_commons.html~`](https://github.com/FOSSersVAST/fossweb/blob/master/creative_commons.html%7E)
* [`deb.html~`](https://github.com/FOSSersVAST/fossweb/blob/master/deb.html%7E)
* [`fedora.html~`](https://github.com/FOSSersVAST/fossweb/blob/master/fedora.html%7E)
* [`gentoo.html`](https://github.com/FOSSersVAST/fossweb/blob/master/gentoo.html%7E)

The task is to remove these files and send a pull request.

**Comment by ambadyanands** [comment]
This issue could be closed since PR #14 solves the issue

**Comment by subins2000** [comment]
After merge of #6 this issue came up again. This is a simple fix, so someone take this ! Let us know if you're working on it (we don't want duplicate works !)

**Comment by ranjithsiji** [comment]
It is better to add those kind of files to gitignore then that will be great

**Comment by subins2000** [comment]
@ranjithsiji it is added to `.gitignore`. But the merge #6 was older. hence those files came back again. And this is a good first issue to work on !

**Comment by subins2000** [comment]
Seems like all such files are removed with #25 . Thanks @Liya777 !
